# =============================================================================
# pr-agent reviewer image, built FROM THIS FORK'S SOURCE.
#
# Drop-in replacement for the previously-running `pragent/pr-agent:0.39.0-github_app`
# image. It intentionally mirrors that image's contract so the captain can swap it
# in without changing ports, env, mounts, or the running command:
#
#   WORKDIR             /app
#   USER                appuser (unprivileged, non-root)
#   ENTRYPOINT          (none)
#   CMD                 python -m gunicorn -k uvicorn.workers.UvicornWorker \
#                           -c pr_agent/servers/gunicorn_config.py \
#                           --forwarded-allow-ips * \
#                           pr_agent.servers.github_app:app
#   EXPOSED PORT        3000/tcp   (gunicorn binds 0.0.0.0:3000 by default)
#   ENV                 PYTHONPATH=/app   (base image vars are inherited)
#
# NO secrets are baked into this image. The GitHub App private key, app id,
# webhook secret and LiteLLM api_base are read at runtime from
#   /app/pr_agent/settings/.secrets.toml   (mounted from ~/.pr-agent/.secrets.toml)
# exactly as the current container expects; `.dockerignore` excludes
# `pr_agent/settings/.secrets.toml` and `**/.env` from the build context.
#
# -----------------------------------------------------------------------------
# Base image: the OFFICIAL python:3.12.13-slim from Docker Hub, pinned by its
# sha256 digest (not a floating tag) so the build is reproducible and tamper-evident.
#
# Digest captured on 2025-08-04 from docker.io/library/python (Docker Hub) via:
#     docker pull python:3.12.13-slim
#     docker inspect --format '{{.RepoDigests}}' python:3.12.13-slim
# => python@sha256:57cd7c3a7a273101a6485ba99423ee568157882804b1124b4dd04266317710de
#
# -----------------------------------------------------------------------------
# Pinning strategy (Finding 1 — floating build dependencies):
#   APT:    package versions pinned to the Debian 13 (trixie) candidates at the
#           base image's release.  The APT *index* is refreshed at every build,
#           but the *versions* installed are pinned.  The APT mirror is not frozen
#           to a Debian snapshot — only the resolved package versions are pinned.
#   Python: all runtime + transitive deps are pinned and hash-verified via
#           requirements.lock, generated by `pip-compile --generate-hashes` (see
#           its header).  Two builds of the same commit produce identical
#           dependency sets.
#
# Privilege drop (Finding 2 — runs as root):
#   The image no longer runs as root.  An unprivileged `appuser` owns /app and
#   the gunicorn CMD starts as that user.  The bind-mounted .secrets.toml must
#   be readable by this UID (e.g. `chmod 644 ~/.pr-agent/.secrets.toml` on host).
# ---------------------------------------------------------------------------
FROM python@sha256:57cd7c3a7a273101a6485ba99423ee568157882804b1124b4dd04266317710de

# APT packages pinned to exact Debian 13 (trixie) versions.  Versions were
# captured with `apt-cache policy` inside the base image; the apt *index* is
# refreshed at every build but the installed *versions* are pinned.  The apt
# lists are cleaned in the same layer to keep the image lean.
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        git=1:2.47.3-0+deb13u1 \
        curl=8.14.1-2+deb13u4 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install dependencies from the hash-pinned lockfile FIRST so this layer is
# cached independently of application source changes.  requirements.lock
# contains every direct and transitive dependency — version-pinned and
# hash-verified — so two builds of the same commit produce identical images.
COPY requirements.lock ./
RUN pip install --no-cache-dir --require-hashes -r requirements.lock

# Copy EVERY build input `pip install .` needs. pyproject.toml declares
# `readme = "README.md"` and `license = { file = "LICENSE" }`, and setuptools
# must find the `pr_agent` package itself; MANIFEST.in ships the pr_agent/*.toml
# settings (and excludes *.secrets.toml). Without these the build yields a
# metadata-only wheel and/or fails -- a metadata-only install was rejected as
# not actually shipping the package. `.dockerignore` keeps `.secrets.toml`/
# `**/.env` out of the context.
COPY pyproject.toml requirements.txt README.md LICENSE MANIFEST.in ./
COPY pr_agent pr_agent

# Install ONLY the pr-agent package itself.  --no-deps because every dependency
# is already pinned and installed above via requirements.lock; without --no-deps
# pip would re-resolve the >= ranges in requirements.txt at build time, which
# defeats the provenance goal.
RUN pip install --no-cache-dir --no-deps . \
    && rm -f pyproject.toml requirements.txt requirements.lock MANIFEST.in

# Keep `pr_agent` in /app so the app runs from source via PYTHONPATH=/app,
# matching the upstream image's runtime layout (build_number.txt lookups, etc.).
ENV PYTHONPATH=/app

# --- Hardening: drop privileges ---
# Create an unprivileged user with a writable home directory.  The home dir is
# needed because some imported libraries (e.g. azure-devops, litellm) create
# cache dirs under $HOME at import time.  The app reads its secrets from a
# bind-mount at /app/pr_agent/settings/.secrets.toml which is NOT in the image
# (.dockerignore excludes it).  The host must make that file readable by this
# UID, e.g. `chmod 644 ~/.pr-agent/.secrets.toml`.  The settings dir in the
# image contains only non-secret .toml files, so it is safe to make it
# world-readable — a bind-mounted file with broader perms then remains
# accessible regardless of the appuser's UID.
RUN groupadd --system appgroup \
    && useradd --system --gid appgroup --shell /bin/sh \
               --home /home/appuser --create-home appuser \
    && chown -R appuser:appgroup /app /home/appuser \
    && chmod -R a+rX /app/pr_agent/settings

ENV HOME=/home/appuser

# Drop to the unprivileged user for all remaining layers and at runtime.
USER appuser

# Same port the upstream image exposes and the captain's run config maps.
EXPOSE 3000

# Same CMD as pragent/pr-agent:0.39.0-github_app. No ENTRYPOINT is set, so
# `docker run` execs gunicorn directly. Per-container runtime values (GitHub App
# key, api_base, PORT, etc.) come from the existing ~/.pr-agent/.secrets.toml
# bind-mount, not from the image.
CMD ["python", "-m", "gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-c", "pr_agent/servers/gunicorn_config.py", "--forwarded-allow-ips", "*", "pr_agent.servers.github_app:app"]
