
# Generated by CodiumAI

import pytest
import yaml
from yaml.scanner import ScannerError

from pr_agent.algo.utils import load_yaml


class TestLoadYaml:
    #  Tests that load_yaml loads a valid YAML string
    def test_load_valid_yaml(self):
        yaml_str = 'name: John Smith\nage: 35'
        expected_output = {'name': 'John Smith', 'age': 35}
        assert load_yaml(yaml_str) == expected_output

    def test_load_invalid_yaml1(self):
        yaml_str = \
'''\
PR Analysis:
  Main theme: Enhancing the `/describe` command prompt by adding title and description
  Type of PR: Enhancement
  Relevant tests: No
  Focused PR: Yes, the PR is focused on enhancing the `/describe` command prompt.

PR Feedback:
  General suggestions: The PR seems to be well-structured and focused on a specific enhancement. However, it would be beneficial to add tests to ensure the new feature works as expected.
  Code feedback:
    - relevant file: pr_agent/settings/pr_description_prompts.toml
      suggestion: Consider using a more descriptive variable name than 'user' for the command prompt. A more descriptive name would make the code more readable and maintainable. [medium]
      relevant line: user="""PR Info: aaa
  Security concerns: No'''
        with pytest.raises(ScannerError):
            yaml.safe_load(yaml_str)

        expected_output = {'PR Analysis': {'Main theme': 'Enhancing the `/describe` command prompt by adding title and description', 'Type of PR': 'Enhancement', 'Relevant tests': False, 'Focused PR': 'Yes, the PR is focused on enhancing the `/describe` command prompt.'}, 'PR Feedback': {'General suggestions': 'The PR seems to be well-structured and focused on a specific enhancement. However, it would be beneficial to add tests to ensure the new feature works as expected.', 'Code feedback': [{'relevant file': 'pr_agent/settings/pr_description_prompts.toml\n', 'suggestion': "Consider using a more descriptive variable name than 'user' for the command prompt. A more descriptive name would make the code more readable and maintainable. [medium]", 'relevant line': 'user="""PR Info: aaa\n'}], 'Security concerns': False}}
        assert load_yaml(yaml_str) == expected_output

    def test_load_invalid_yaml2(self):
        yaml_str = '''\
- relevant file: src/app.py:
  suggestion content: The print statement is outside inside the if __name__ ==: \
'''
        with pytest.raises(ScannerError):
            yaml.safe_load(yaml_str)

        expected_output = [{'relevant file': 'src/app.py:\n', 'suggestion content': 'The print statement is outside inside the if __name__ ==:'}]
        assert load_yaml(yaml_str) == expected_output

    # Tests that a fenced block whose info string is separated by a space
    # (CommonMark allows whitespace after the opening fence) parses the same
    # as the flush form.
    def test_space_before_yaml_info_string(self):
        expected = {"name": "John"}

        assert load_yaml("```yaml\nname: John\n```") == expected
        assert load_yaml("``` yaml\nname: John\n```") == expected
        assert load_yaml("``` yml\nname: John\n```") == expected

    # A fence labeled with a non-YAML info string (e.g. ```text or ```python)
    # must not be extracted and parsed as a YAML snippet. The old pattern's
    # optional (yaml|yml) group let any info string through, so the body
    # started with the stray label and a plain-scalar body came back as a
    # folded string instead of None.
    def test_non_yaml_info_string_not_parsed_as_yaml_snippet(self):
        assert load_yaml("```text\nhello world\n```") is None
        assert load_yaml("```python\nname: John\n```") is None

    # A fenced block that only becomes reachable through the snippet fallback
    # (the initial parse fails because of surrounding text) must be extracted
    # and parsed, not crash on a stale group index.
    def test_snippet_fallback_with_surrounding_text(self):
        expected = {"name": "John"}
        assert load_yaml("prefix text\n```yaml\nname: John\n```") == expected
        assert load_yaml("prefix text\n``` yaml\nname: John\n```") == expected
